# Generated by Django 5.0.4 on 2024-04-26 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HardSkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='hardskills')),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='softskills')),
            ],
        ),
        migrations.CreateModel(
            name='SpecializationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Специальность')),
            ],
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Заказчик')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/users/%Y/%m/%d', verbose_name='Фото')),
                ('number', models.CharField(max_length=12, verbose_name='Номер')),
                ('messages', models.TextField(blank=True, verbose_name='Соц.сети')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='День рождение')),
                ('photo', models.ImageField(blank=True, upload_to='image/users/%Y/%m/%d', verbose_name='Фото')),
                ('number', models.CharField(max_length=12, verbose_name='Номер')),
                ('messages', models.TextField(blank=True, verbose_name='Соц.сети')),
                ('description', models.TextField(blank=True, verbose_name='О себе')),
                ('experience', models.CharField(blank=True, max_length=150, verbose_name='Опыт работы')),
                ('link_resume', models.TextField(blank=True, verbose_name='Ссылки на резюме/ГИТ/ и т.д.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('hardskills', models.ManyToManyField(blank=True, related_name='hard', to='dagfreelance.hardskillsmodel', verbose_name='профессиональные навыки')),
                ('softskills', models.ManyToManyField(blank=True, related_name='soft', to='dagfreelance.softskillsmodel', verbose_name='гибкие навыки')),
                ('specialization', models.ManyToManyField(blank=True, related_name='specialization', to='dagfreelance.specializationmodel', verbose_name='Специализация')),
            ],
        ),
    ]
